##
# testing
##
test:units:
  stage: test
  image: php:7.4.0

  cache:
    paths:
      - vendor/

  # see https://gist.github.com/giansalex/2776a4206666d940d014792ab4700d80 for docker php extension list
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libxpm-dev zlib1g-dev unixodbc-dev libsqlite3-dev
    - docker-php-ext-install pdo_mysql opcache
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - php composer.phar install
  script:
    - bin/phpunit --coverage-text --colors=never
  only:
    - develop
    - master
  when: manual